/// Flutter icons StoIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StoIcons
///      fonts:
///       - asset: fonts/StoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StoIcons {
  StoIcons._();

  static const _kFontFam = 'StoIcons';
  static const _kFontPkg = null;

  static const IconData profile_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData request_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData services_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
